baseURL = "https://unaudited.felixjen.com"
languageCode = "en-us"
title = "Unaudited"
theme = "pixyll"

author = "Felix Jen"
enableEmoji = true
DefaultContentLanguage = "en"

[params]
  paginate = 8
  google_analytics_id = "UA-118000647-1"

copyright = "Copyright (c) 2013-2018, Felix Jen; all rights reserved."
