baseURL = "https://www.rule12b6.com"
languageCode = "en-us"
title = "Rule 12(b)(6)"
theme = "pixyll"

author = "Felix Jen"
enableEmoji = true
DefaultContentLanguage = "en"

[params]
  paginate = 8
  google_analytics_id = ""

copyright = "Copyright (c) 2020-2020, Felix Jen; all rights reserved."
